---
# Sets up the operating system for Quagga's installation process
- name: Make Quagga user group=quagga
  group: name="{{ quagga_group }}"

- name: Add Quagga user
  user: name="{{ quagga_user }}" group="{{ quagga_group }}" createhome=no

- name: Make directory for quagga installation
  file: path="{{ quagga_directory }}" state=directory

- name: Set the owner of the directory
  shell: chown {{ quagga_user }}:{{ quagga_group }} {{ quagga_directory }}

- name: Copy and Unpack Quagga
  unarchive: src="{{ quagga_version }}.tar.gz" dest="{{ dependency_directory }}" creates="{{ dependency_directory }}/{{ quagga_version }}.tar.gz/README"

- name: Configure Quagga
  shell: ./configure --sysconfdir={{ quagga_directory }} --localstatedir={{ quagga_directory }}
  args:
    chdir: "{{ dependency_directory }}/{{ quagga_version }}"

- name: Make Quagga
  shell: make
  args:
    chdir: "{{ dependency_directory }}/{{ quagga_version }}"

- name: Install Quagga
  shell: make install
  args:
    chdir: "{{ dependency_directory }}/{{ quagga_version }}"

- name: Clean up after Quagga
  shell: make distclean
  args:
    chdir: "{{ dependency_directory }}/{{ quagga_version }}"